### PR TITLE
sip

### PR DESCRIPTION
**Pull request by arbitrxfund**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

1. Create a folder under `/tokens`, the folder name is your token symbol in the `lowercase` format

2. Upload your logo in your folder

- [x] Filename in the `uppercase` format with suffix
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

3. Upload a json file for additional info. File name is your token symbol in the `uppercase` format with suffix

* `asset` must be your token's symbol
* `assetMap` must be your token's symbol without suffix
* `market` must be `ALTS` or `FIAT`. It determines which market the pair will be listed in when this token is the quote symbol.
* `display`'s default value is `true`, which means the information will be available in the explorer

The following contacts are supported in `contact`:
* Twitter
* Facebook
* Reddit
* Instagram
* Medium
* Steemit
* Coinmarketcap
* Binance Info
* Youtube
* Telegram
* Discord
* Linkedin
* Github
* Binance Research

> Note: you must use the right key name

Example:

```json
{
    "asset":"SIP-2CEM",
    "assetMap":"SIP",
    "market": "ALTS",
    "officialSiteUrl":"https://arbitrx.fund/",
    "contactEmail":"info@arbitrx.fund",
    "display":true,
    "contact":{
        "Telegram":"https://t.me/arbitrxfund",
        "Medium":"https://medium.com/@arbitrxfund",
        "Twitter":"https://twitter.com/arbitrxfund",
        "Github":"https://github.com/arbitrxfund/"
    }
}

```

### CODE REVIEW

**Review by huangsuyu — CHANGES_REQUESTED** [review]
Please add a proper json file

**Comment by arbitrxfund** [comment]
hi thanks for your message there is another one "Add SIP-2CEM #2"  kindly look into it

**Comment by huangsuyu** [comment]
> hi thanks for your message there is another one "Add SIP-2CEM" kindly look into it

Sorry, I cannot see it in your PR files

**Comment by arbitrxfund** [comment]
https://github.com/billyeun/tokens-info/tree/3344d09f41ea8efc5871777498b1b38d55948a22/tokens/sip

**Comment by arbitrxfund** [comment]
doing new

**Pull request closed without merging**
