### PR TITLE
add bhc

### PR DESCRIPTION
**Pull request by BHCHappiness**
{
    "asset”:”BHC-3E8M”,
    "assetMap":"BHC",
    "market": “FIAT”,
    "officialSiteUrl":"https://billionhappiness.com/“,
    "contactEmail”:”billionhappiness@gmail.com”,
    "display":true,
    "contact":{
        "Telegram":"https://t.me/BillionHappinessOfficial",
        “Instagram”:”https://instagram.com/billion_happiness”,
        "Twitter":"https://twitter.com/BHC_Happiness”, 			
        "Facebook":"https://www.facebook.com/BillionHappiness/“
    }
}

### CODE REVIEW

**Review by chainwhisper — CHANGES_REQUESTED** [review]
Please update your file, this is an example: https://github.com/binance-chain/tokens-info/pull/107/files

**Comment by billyeun** [comment]
@huangsuyu Hello friend, done editing, please check and let me know. Thank you

**Review by chainwhisper — CHANGES_REQUESTED** [review]
Hello,

You json is still under the wrong format. 

Please correct the double quotes.

**Comment by billyeun** [comment]
I deleted the wrong one please check it

**Comment by huangsuyu** [comment]
> I deleted the wrong one please check it

No, you don't need to delete the json file. You just need to correct the double-quotes.

**Pull request closed without merging**
